# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# Testing manually adding the secrets

name: Build and deploy container app to Azure Web App - ai-rfp-agentic-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testopenaicarlos-g8c9b7hab9dzazeh.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_test }}
        password: ${{ secrets.AzureAppService_ContainerPassword_test }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testopenaicarlos-g8c9b7hab9dzazeh.azurecr.io/ai-rfp-agentic/aoai-gpt-agentic-webapp:${{ github.sha }}
        file: ./WebApp.Dockerfile

  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up Python version
  #       env:
  #         AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
  #         AZURE_OPENAI_MODEL: ${{ secrets.AZURE_OPENAI_MODEL }}
  #       uses: actions/setup-python@v1
  #       with:
  #         python-version: '3.11'

  #     - name: Create and start virtual environment
  #       run: |
  #         python -m venv venv
  #         source venv/bin/activate
      
  #     - name: Install dependencies
  #       run: pip install -r requirements.txt
        
  #     # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

  #     - name: Zip artifact for deployment
  #       run: zip release.zip ./* -r

  #     - name: Upload artifact for deployment jobs
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: python-app
  #         path: |
  #           release.zip
  #           !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ai-rfp-agentic-webapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_test }}
        images: 'testopenaicarlos-g8c9b7hab9dzazeh.azurecr.io/ai-rfp-agentic/aoai-gpt-agentic-webapp:${{ github.sha }}'
